### ISSUE TITLE
BUG - Incorrect spells in holy mountain + webassembly not available 

### ISSUE THREAD

**Issue by hyunki** [TwoAbove/noita-tools#110] opened 2022-02-03 08:14 UTC
**Describe the bug**

**To Reproduce**
Thank you for the great app.
  
  https://noita-tools.herokuapp.com/
  Input seed submit button doesn't work on Edge Browser. It works on firefox and chrome.

plus, shop itmes appear on site are completely different from the game.
![image](https://user-images.githubusercontent.com/25163778/152330428-f881f51d-1e59-4011-aaea-b8aa852b2890.png)

Submit button display below error report.

no native wasm support detected
noita_random.js:11 
        
       Uncaught (in promise) ReferenceError: WebAssembly is not defined
    at ee (noita_random.js:11:29531)
    at noita_random.js:11:17345
    at random.ts:78:38
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at n (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)

익명 means "anonymous"
비동기 means "Asynchrony, asynchronous"

![image](https://user-images.githubusercontent.com/25163778/152304930-89013b8e-c940-411d-9f36-317aa3f9304f.png)
constant loading.

![image](https://user-images.githubusercontent.com/25163778/152304991-3c15bafd-38d1-4041-9a4b-e0eeddd526d7.png)
![image](https://user-images.githubusercontent.com/25163778/152305053-7d3b570b-1878-4268-95fc-c0bb46eb36da.png)
![image](https://user-images.githubusercontent.com/25163778/152305129-31b611bd-47ab-4e69-9198-2ffa021ce972.png)

**Comment by TwoAbove** [comment] 2022-02-04 21:54
@hyunki Thank you for the bug report! Can you also provide the seed that doesn't have the correct spells?

**Comment by TwoAbove** [comment] 2022-02-04 21:56
Also, what version of Edge are you using?

**Comment by hyunki** [comment] 2022-02-04 22:16
@TwoAbove Hi, Thank you for the great app.
Edge version was 97.0.1072.76 (official build) (64bit)
game seed was 457440497
no mod applied. Everything(wands, perks) seems fine except that shop spells.

**Comment by TwoAbove** [comment] 2022-02-11 05:13
I'm back from a break and am working on this.

I'll message you once a fix is deployed

**Comment by TwoAbove** [comment] 2022-02-13 04:22
@hyunki I think I know what the issue is with the spells. Do you know which spells you have unlocked and which ones you don't?

**Comment by hyunki** [comment] 2022-02-13 19:28
> @hyunki I think I know what the issue is with the spells. Do you know which spells you have unlocked and which ones you don't?

Oh.. I got it. 
I thought I unlocked all. but actually it's only 80% of 'em.
The site meant for 100% progress. right?

**Comment by TwoAbove** [comment] 2022-02-14 04:36
Yes, I don't take into account if a spell is unlocked or not - I'd look into [unlockable spells](https://noita.fandom.com/wiki/Unlockable_spells) and check which ones you already have unlocked. If you don't have some of those - please paste them here so I can check whether ignoring them during generation will get the correct result

**Comment by TwoAbove** [comment] 2022-03-08 21:26
So it turns out, after much digging in the exe, that unlocked spells are actually taken into account. So this bugfix requires several things, mainly implementing the config storage from https://github.com/TwoAbove/noita-tools/issues/125, and then updating the cpp code to take your unlocked spells into account.

**Comment by TwoAbove** [comment] 2022-04-24 16:34
I'll close this because the bug part is now fixed – the tool checks for webassembly availability

**Comment by hyunki** [comment] 2022-04-24 18:25
> 

It doesn't even display anything

**Comment by TwoAbove** [comment] 2022-04-26 15:09
Huh, Thank you! I'll re-open this and try to fix this ASAP

**Comment by TwoAbove** [comment] 2022-05-26 00:03
Sorry I didn't update this issue - I've updated the page to better show the Edge error which is a too locked down browser issue. Noitool requires WebAssembly to run, so I can't do anything when the browser disallows WASM

**Closed by TwoAbove** 2022-05-26 00:03 UTC
Labels: bug, enhancement
